### ISSUE TITLE
Vertical Alignment

### ISSUE THREAD

**Issue by suwigyarathore** [jekorx/vue-carousel-card#1]
First of all, I want to say thank you for great component you wrote here. I work seamlessly.
The only problem I am facing is with vertical alignment. As for all cards, I am filling dynamic data whose height is auto. As the position of all cards is absolute it's tricky to vertically align them.

I suggest making below change in **vue-carousel-card/src/carousel-card/src/item.vue** on line 5

**From**

` :style="{
      msTransform: `translateX(${ translate }px) scale(${ scale })`,
      webkitTransform: `translateX(${ translate }px) scale(${ scale })`,
      transform: `translateX(${ translate }px) scale(${ scale })`
    }"`

**To**
` :style="{
      msTransform: `translateX(${ translate }px) translateY(-50%)  scale(${ scale })`,
      webkitTransform: `translateX(${ translate }px) scale(${ scale })`,
      transform: `translateX(${ translate }px) scale(${ scale })`,
      top: 50%
    }"`

Your help will be greatly appreciated :)

**Comment by jekorx** [comment]
@suwigyarathore Thank you very much for your suggestion. I have revised the above issues and released a new version 1.0.3.
